spring:
  application:
    name: usian-search-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    elasticsearch:
      cluster-boddes: 192.168.111.128:9200
server:
  port: 8095
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.usian.pojo
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
